### ISSUE TITLE
Slight correction in instructions (lights.py => light.py)

### ISSUE THREAD

**Issue by jgoldwein** [htvekov/openHASP-APDS9930-proximity-sensor-Custom-Code#1]
Hello and thanks for doing this.  I will be trying to incorporate the program in my openHASP device.   May I suggest you change "lights.py" to "light.py" in your installation instructions.  I am kind of a "newbie" and this was confusing to me so I suspect it could be for others as well.   I realize it is a "nit", but hopefully you will understand.   

Thanks again.  

JG

**Comment by htvekov** [comment]
You're welcome :-)
I've now corrected the spelling error in the documentation.
